<h1>
	 Dashboard
</h1>


<div class="bloc">
    <div class="title">
        
    <a class="toggle" href="#"></a></div>
    <div class="content">
        <a class="shortcut" href="<?php echo $this->baseUrl(); ?>/admin/student">
            <img alt="" src="<?php echo $this->baseUrl(); ?>/includes/img/icons/font.png">
            Manage Student Details
        </a>
        <a class="shortcut" href="<?php echo $this->baseUrl(); ?>/admin/course">
            <img width="32" height="32" alt="" src="<?php echo $this->baseUrl(); ?>/includes/img/icons/window.png">
           Manage Course Details
        </a>
        <a class="shortcut" href="<?php echo $this->baseUrl(); ?>/admin/unit">
            <img width="32" height="32" alt="" src="<?php echo $this->baseUrl(); ?>/includes/img/icons/warning.png">
             Manage Unit Details
        </a>
       
        <div class="cb"></div>
    </div>
</div>



