<?php
$this->headLink ()->appendStylesheet ( $this->baseUrl () . '/includes/css/style.css' );
$this->headLink ()->appendStylesheet ( $this->baseUrl () . '/includes/js/datepick/jquery.datepick.css' );
$this->headLink ()->appendStylesheet ( $this->baseUrl () . '/includes/content/settings/style.css' );
$this->headLink ()->appendStylesheet ( $this->baseUrl () . '/includes/js/jwysiwyg/jquery.wysiwyg.old-school.css' );
//$this->headLink ()->appendStylesheet ( $this->baseUrl () . '/includes/js/DataTables/media/css/demo_table.css' );
//$this->headLink ()->appendStylesheet ( $this->baseUrl () . '/includes/js/DataTables/media/css/jquery.dataTables.css' );
$this->headLink ()->appendStylesheet ( $this->baseUrl () . '/kendoui/styles/kendo.common.min.css' );
$this->headLink ()->appendStylesheet ( $this->baseUrl () . '/kendoui/styles/kendo.default.min.css' );

?>
<?php

$this->headScript ()->appendFile ( $this->baseUrl () . '/includes/js/cookie/jquery.cookie.js' );
$this->headScript ()->appendFile ( $this->baseUrl () . '/includes/js/jwysiwyg/jquery.wysiwyg.js' );
$this->headScript ()->appendFile ( $this->baseUrl () . '/includes/js/tooltipsy.min.js' );
$this->headScript ()->appendFile ( $this->baseUrl () . '/includes/js/iphone-style-checkboxes.js' );
$this->headScript ()->appendFile ( $this->baseUrl () . '/includes/js/excanvas.js' );
$this->headScript ()->appendFile ( $this->baseUrl () . '/includes/js/zoombox/zoombox.js' );
$this->headScript ()->appendFile ( $this->baseUrl () . '/includes/js/visualize.jQuery.js' );
$this->headScript ()->appendFile ( $this->baseUrl () . '/includes/js/jquery.uniform.js' );
$this->headScript ()->appendFile ( $this->baseUrl () . '/includes/js/main.js' );
$this->headScript ()->appendFile ( $this->baseUrl () . '/includes/content/settings/main.js' );

$this->headScript ()->appendFile ( $this->baseUrl () . '/includes/js/datepick/jquery.datepick.js' );
//$this->headScript()->appendFile($this->baseUrl () . '/includes/js/DataTables/media/js/jquery.dataTables.js' );
$this->headScript ()->appendFile ( $this->baseUrl () . '/kendoui/js/kendo.web.min.js' );
$this->headScript ()->appendFile ( $this->baseUrl () . '/kendoui/js/cultures/kendo.culture.en-GB.min.js' );

?>

<?php print $this->doctype(); ?>
<html>
<head>
	<?php print $this->headMeta(); ?>
	<?php print $this->headTitle(); ?>

	<?php
	
	if ($this->jQuery ()->isEnabled ()) {
		
		print $this->jQuery ();
	}
	
	?>
	
	 <?php
		print $this->headLink ();
		?>
		
        <?php
								print $this->headScript ();
								?>
<script>

$(function(){
	kendo.culture("en-GB");
	});
	var baseUrl = "<?php echo $this->baseUrl();?>";
								</script>
								
</head>
<body>




	<div class="settings" id="settings">
		<div class="wrapper">
			<div class="grid3">
				<div class="titre">Backgrounds</div>
				<a
					href="url(<?php echo $this->baseUrl();?>/includes/css/img/bg.png)"
					class="backgroundChanger active" title="White"></a> <a
					href="url(<?php echo $this->baseUrl();?>/includes/css/img/dark-bg.png)"
					class="backgroundChanger dark" title="Dark"></a> <a
					href="url(<?php echo $this->baseUrl();?>/includes/css/img/wood.jpg) fixed"
					class="backgroundChanger dark" title="Wood"></a> <a
					href="url(<?php echo $this->baseUrl();?>/includes/css/img/altbg/smoothwall.png)"
					class="backgroundChanger" title="Smoothwall"></a> <a
					href="url(<?php echo $this->baseUrl();?>/includes/css/img/altbg/black_denim.png) fixed"
					class="backgroundChanger dark" title="black_denim"></a> <a
					href="url(<?php echo $this->baseUrl();?>/includes/css/img/altbg/carbon.gif) fixed"
					class="backgroundChanger dark" title="Carbon"></a> <a
					href="url(<?php echo $this->baseUrl();?>/includes/css/img/altbg/double_lined.png) fixed"
					class="backgroundChanger" title="Double lined"></a>
				<div class="clear"></div>
			</div>
			<div class="grid3">
				<div class="titre">Bloc style</div>
				<a href="black" class="blocChanger" title="Black"
					style="background: url(<?php echo $this->baseUrl();?>/includes/css/img/bloctitle.png);"></a>
				<a
					href="white" class="blocChanger active" title="White"
					style="background: url(<?php echo $this->baseUrl();?>/includes/css/img/white-title.png);"></a>
				<a
					href="wood" class="blocChanger" title="Wood"
					style="background: url(<?php echo $this->baseUrl();?>/includes/css/img/wood-title.jpg);"></a>
				<div class="clear"></div>
			</div>
			<div class="grid3">
				<div class="titre">Sidebar style</div>
				<a href="grey" class="sidebarChanger active" title="Grey"
					style="background: #494949"></a> <a href="black"
					class="sidebarChanger" title="Black" style="background: #262626"></a>
				<a href="white" class="sidebarChanger" title="White"
					style="background: #EEEEEE"></a>
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
		</div>
		<a class="settingbutton" href="#"> </a>
	</div>
	<!--              
                HEAD
                        -->
	<div id="head">
		<div class="left">
			<!-- <a href="#" class="logo"><img
				src="<?php echo $this->baseUrl();?>/includes/img/logo.png" alt=""></a> -->
			<a href="<?php echo $this->url(array('module'=>'default', 'controller'=>'index', 'action' => 'index'), null , true);?>" class="button profile"><img
				src="<?php echo $this->baseUrl();?>/includes/img/icons/top/huser.png"
				alt="" /></a> 
				
				<?php
				
				if (Zend_Auth::getInstance ()->hasIdentity ()) {
					
					$result = Zend_Auth::getInstance ()->getIdentity ();
					
					?>

				
				
				
				Hi, <a href="javascipt:void(0);"><?php echo $result->username; ?></a> 
			
			
					
			| <a	href="<?php echo $this->url(array('module'=>'login', 'controller'=>'login', 'action' => 'logout'), null , false);?>">Logout</a>
<?php
				
				}
				?>
				</div>
		<div class="right">
			
		</div>
	</div>


	<!--            
                SIDEBAR
                         -->
	<div id="sidebar">
					<?php
					$partial = 'menu.phtml';
					$this->navigation ()->menu ()->setPartial ( $partial );
					//$this->navigation ()->menu ()->setMaxDepth ( 2 );
					echo $this->navigation ()->menu ()->render ();
					?>

	</div>




	<!--            
              CONTENT 
                        -->
	<div class="white" id="content">
	<?php
	print $this->render ( 'message.phtml' );
	?>
	
	<?php
	print $this->layout ()->content;
	?>
</div>

</body>
</html>
